### PR TITLE
chore: update to actual nodejs versions

### PR DESCRIPTION
**Pull request by abtris**
- [x] test in actual NodeJS version

### CODE REVIEW

**Comment by kylef** [comment]
There is an older supported version in `package.json` that perhaps should now be `> 6.0` to match the tested environment:

```json
  "engines": {
    "node": ">= 0.6.0"
  },
```

**Comment by abtris** [comment]
@kylef updated, but we need find way how fix that problem in https://github.com/apiaryio/Amanda/blob/master/src/engines/json/attributes/format.js#L102

**Comment by abtris** [comment]
@kylef some idea how replace this with safe regex for uri? I'm not sure if this regex with domains can work with actual plenty custom root domains.

**Comment by abtris** [comment]
@kylef @char0n I try replace regex with simplest form or use rfc3986 npm package but still some issue. Looks as custom domains not going thru. Advice?

**Comment by char0n** [comment]
In this case I'd try the last resort and that is https://github.com/chriso/validator.js. There is an `isUrl` functions that is configurable with options. I've been using it successfully in the past.

**Comment by abtris** [comment]
Amanda is too permissive. URI don't need protocol for example. I'm not sure if we can change without breaking changes.

**Comment by char0n** [comment]
@abtris yes this should be possible with isURL
```js
isURL('http://test.cz', { require_tld: false, require_protocol: false .... });
```

**Comment by abtris** [comment]
@char0n can you look how we can modify Amanda to use `isURL`. Now there are directly used Regexp not function.

**Comment by char0n** [comment]
Will try, still have some 2 hours of platform to go.

**Comment by abtris** [comment]
@char0n free to pass to next platform

**Comment by abtris** [comment]
@char0n I make cleanup and remove all not used things. This PR just update dev dependecies for node 6,8 and make valid package.json for latest npm.

**Review by char0n — APPROVED** [review]

**Pull request merged**
